UPDATE: improved `git clone` commands across multiple config files
this commit makes 2 changes to all `git clone` commands in this repo:
- all `git clone` commands are now `git clone -o github`:
    - this will name the "origin" remote as `github`, instead of `origin`
- all `git clone` commands will now, if they fail, output "error" messages to the `pkg_fail.txt` file

diff --git a/src/lib/60-deploy_dotfiles b/src/lib/60-deploy_dotfiles
--- a/src/lib/60-deploy_dotfiles
+++ b/src/lib/60-deploy_dotfiles
@@ -4,7 +4,8 @@ deploy_dotfiles() {
     echo "[INFO]: Deploying dotfiles."
 
     sudo -u "$user_name" mkdir -p "$REPODIR"
-    sudo -u "$user_name" git clone https://github.com/DavidVogelxyz/bin-linux "$REPODIR/bin-linux" > /dev/null 2>&1
+    sudo -u "$user_name" git clone -o github https://github.com/DavidVogelxyz/bin-linux "$REPODIR/bin-linux" > /dev/null 2>&1 \
+        || echo "[ERROR]: Failed to \`git clone\` the \`bin-linux\` repo." >> "${WORK_DIR}/pkg_fail.txt"
     sudo -u "$user_name" bash "$REPODIR/bin-linux/bin-linux/dotfile-deploy" > /dev/null 2>&1
 
     local files=(
diff --git a/src/lib/67-setup_zsh b/src/lib/67-setup_zsh
--- a/src/lib/67-setup_zsh
+++ b/src/lib/67-setup_zsh
@@ -25,10 +25,12 @@ config_zsh() {
     echo "[INFO]: Configuring \`zsh\`."
 
     sudo -u "$user_name" git clone \
+        -o github \
         --depth=1 \
         https://github.com/romkatv/powerlevel10k \
         "$REPODIR/powerlevel10k" \
-        > /dev/null 2>&1
+        > /dev/null 2>&1 \
+        || echo "[ERROR]: Failed to \`git clone\` the \`powerlevel10k\` repo." >> "${WORK_DIR}/pkg_fail.txt"
 
     local fonts=(
         "MesloLGS_NF_Regular.ttf"
